
-- Update aptitude topics with rich descriptions
UPDATE aptitude_topics SET
  description = CASE name
    WHEN 'Percentage' THEN 'Percentage is a way of expressing a number as a fraction of 100. Used extensively in profit/loss, discounts, interest calculations, and data interpretation. Key formulas: Percentage = (Value/Total) × 100. Percentage change = ((New - Old)/Old) × 100. If A is X% more than B, then B is (X/(100+X))×100% less than A.'
    WHEN 'Profit and Loss' THEN 'Profit and Loss concepts are fundamental for business and financial aptitude. Profit = SP - CP. Loss = CP - SP. Profit% = (Profit/CP) × 100. If successive discounts are a% and b%, effective discount = (a + b - ab/100)%. Marked price and discount relationships are crucial for competitive exams.'
    WHEN 'Simple Interest' THEN 'Simple Interest (SI) = (P × R × T) / 100, where P = Principal, R = Rate per annum, T = Time in years. Amount = P + SI. SI is directly proportional to all three variables. Commonly tested with compound scenarios and comparisons.'
    WHEN 'Compound Interest' THEN 'Compound Interest grows exponentially. A = P(1 + R/100)^T. CI = A - P. When compounded half-yearly: A = P(1 + R/200)^(2T). Difference between CI and SI for 2 years = P(R/100)^2. For 3 years the difference formula is more complex. Rule of 72: time to double = 72/R.'
    WHEN 'Time and Work' THEN 'If A can do a job in x days, A''s 1-day work = 1/x. If A and B work together, combined rate = 1/x + 1/y. LCM method simplifies calculations: assume total work = LCM(days). Pipes and cisterns follow the same logic — filling pipes are positive, drain pipes are negative. Efficiency ratios are key.'
    WHEN 'Time, Speed and Distance' THEN 'Speed = Distance/Time. Average speed for equal distances = 2xy/(x+y). Relative speed: same direction = |v1 - v2|, opposite = v1 + v2. Train problems: time to cross a pole = length/speed. Time to cross platform = (train + platform length)/speed. Boats & streams: downstream = u+v, upstream = u-v.'
    WHEN 'Ratio and Proportion' THEN 'A ratio a:b compares two quantities. Proportion: a:b = c:d means ad = bc. Componendo: (a+b):(a-b). Dividendo: same concept. Mixture and alligation: find the ratio of mixing two solutions. Mean proportion of a and b = √(ab). Continued proportion: a:b = b:c so b² = ac.'
    WHEN 'Averages' THEN 'Average = Sum of observations / Number of observations. Weighted average: ΣwiXi / Σwi. If the average of n numbers is A and a new number x is added, new average = (nA + x)/(n+1). When one element is replaced, change in average = change in value/n. Arithmetic Mean, Median, and Mode differences are tested.'
    WHEN 'Number System' THEN 'Covers divisibility rules, HCF, LCM, remainders, and number properties. Divisibility: by 2 (even), 3 (digit sum divisible by 3), 4 (last two digits), 7, 11 (alternating sum), 13. HCF × LCM = Product of two numbers. Cyclicity of units digits. Remainder theorem and Fermat''s little theorem are advanced topics.'
    WHEN 'Permutations and Combinations' THEN 'Permutation (order matters): P(n,r) = n!/(n-r)!. Combination (order doesn''t matter): C(n,r) = n!/[r!(n-r)!]. Circular permutations = (n-1)!. Identical objects: n!/(p!q!r!). Selecting at least one from n: 2^n - 1. Stars and Bars method for distributing identical objects. Derangements.'
    WHEN 'Probability' THEN 'Probability P(E) = Favorable outcomes / Total outcomes. P(A∪B) = P(A) + P(B) - P(A∩B). P(A|B) = P(A∩B)/P(B). Independent events: P(A∩B) = P(A)·P(B). Bayes'' theorem for conditional probability. Geometric probability. Expected value = ΣP(x)·x. Binomial distribution for repeated trials.'
    WHEN 'Data Interpretation' THEN 'Analyze tables, bar charts, pie charts, line graphs, and mixed charts. Key skills: calculating percentages, ratios, growth rates, and comparisons. Watch for approximate calculations to save time. Common question types: find the value, compare, find the percentage change, rank the categories, and find total or average.'
    ELSE description
  END
WHERE name IN ('Percentage', 'Profit and Loss', 'Simple Interest', 'Compound Interest', 'Time and Work',
               'Time, Speed and Distance', 'Ratio and Proportion', 'Averages', 'Number System',
               'Permutations and Combinations', 'Probability', 'Data Interpretation');

-- Update DSA topics with rich descriptions
UPDATE dsa_topics SET
  description = CASE name
    WHEN 'Arrays' THEN 'An array is a contiguous block of memory storing elements of the same type, accessed by index in O(1). Arrays are the foundation of most data structures. Key operations: traversal O(n), insertion/deletion O(n), search O(n) linear or O(log n) binary. Two-pointer and sliding window techniques solve many array problems. Subarray problems use prefix sums and Kadane''s algorithm for maximum subarray sum.'
    WHEN 'Linked Lists' THEN 'A linked list is a dynamic data structure of nodes, each containing data and a pointer to the next node. Types: Singly (one direction), Doubly (both directions), Circular. Operations: insert/delete at head O(1), at tail O(n) for singly. Key algorithms: Floyd''s cycle detection, reversing a linked list, finding middle node (slow/fast pointers), merging sorted lists, and cloning with random pointers.'
    WHEN 'Stacks' THEN 'A stack is a LIFO (Last In First Out) data structure. Push and pop operations are O(1). Implemented via arrays or linked lists. Applications: function call stack, expression evaluation (infix to postfix), balanced parentheses, browser history, undo/redo. Monotonic stacks solve "next greater/smaller element" problems in O(n). Daily Temperatures, Stock Span, Largest Rectangle in Histogram.'
    WHEN 'Queues' THEN 'A queue is a FIFO (First In First Out) structure with enqueue and dequeue in O(1). Variants: Circular Queue (avoids wasted space), Deque (double-ended), Priority Queue (heap-based, O(log n) ops). Applications: BFS traversal, CPU scheduling, task processing. Sliding Window Maximum uses a monotonic deque. Implement Queue using two Stacks is a classic interview question.'
    WHEN 'Trees' THEN 'A tree is a hierarchical structure with a root, parent-child relationships, and no cycles. Binary Tree: each node has at most 2 children. BST: left < root < right, O(log n) ops if balanced. Traversals: Inorder (sorted for BST), Preorder, Postorder, Level-order (BFS). AVL and Red-Black trees maintain balance. Height, diameter, lowest common ancestor (LCA), and path sum problems are must-know.'
    WHEN 'Graphs' THEN 'A graph consists of vertices (V) and edges (E). Representations: Adjacency Matrix O(V²) space, Adjacency List O(V+E). Traversals: BFS (shortest path in unweighted), DFS (connectivity, cycle detection, topological sort). Dijkstra''s for weighted shortest path O((V+E)log V). Bellman-Ford handles negative weights. Kruskal/Prim for MST. Union-Find for connected components.'
    WHEN 'Dynamic Programming' THEN 'DP solves problems by breaking them into overlapping subproblems and storing results (memoization/tabulation). Identify DP when the problem has optimal substructure and overlapping subproblems. Classic problems: Fibonacci, 0/1 Knapsack, Longest Common Subsequence, Edit Distance, Matrix Chain Multiplication, Coin Change, Longest Increasing Subsequence. State design and transition equations are critical skills.'
    WHEN 'Sorting Algorithms' THEN 'Sorting is fundamental. Comparison sorts: Bubble O(n²), Selection O(n²), Insertion O(n²) [good for nearly sorted], Merge O(n log n) [stable], Quick O(n log n) avg [in-place, unstable], Heap O(n log n). Non-comparison sorts: Counting O(n+k), Radix O(nk), Bucket O(n+k). Stability matters when sorting objects with multiple fields. Know when to use each sort.'
    WHEN 'Searching Algorithms' THEN 'Linear Search O(n): works on unsorted arrays. Binary Search O(log n): requires sorted array, eliminate half each step. Variants: first/last occurrence, search in rotated sorted array, search in 2D matrix, find peak element, finding minimum in rotated array. Ternary search for unimodal functions. Exponential search for unbounded arrays. Most powerful algorithmic technique after DP.'
    WHEN 'Hashing' THEN 'Hash tables provide O(1) average-case for insert, delete, search. Hash function maps keys to indices. Collision resolution: Chaining (linked list) or Open Addressing (linear/quadratic probing, double hashing). Load factor α = n/m; rehashing when α exceeds threshold. Applications: frequency counting, two-sum, anagram detection, LRU cache, group anagrams, substring problems with fixed/sliding windows.'
    WHEN 'Recursion' THEN 'Recursion solves problems by calling the same function with smaller input. Base case stops recursion; recursive case reduces the problem. Call stack grows with depth. Tail recursion can be optimized. Backtracking = recursion + pruning: N-Queens, Sudoku, subsets, permutations. Convert recursion to iteration using an explicit stack. Time complexity via recurrence relations (Master Theorem).'
    WHEN 'Heaps' THEN 'A heap is a complete binary tree satisfying the heap property. Min-Heap: parent ≤ children; Max-Heap: parent ≥ children. Insert and delete O(log n); findMin/findMax O(1). Built-in as Python''s heapq, Java''s PriorityQueue. Applications: Kth largest/smallest, merge K sorted lists, task scheduling (OS), Dijkstra, Prim. Heapify builds a heap in O(n). Heap sort is O(n log n) in-place.'
    WHEN 'String Algorithms' THEN 'Strings are arrays of characters with special algorithms. Palindrome check, anagram detection, reverse. Pattern matching: Naive O(nm), KMP O(n+m) using failure function, Rabin-Karp O(n+m) rolling hash. Trie for prefix-based dictionary/autocomplete. Z-algorithm for string matching. Longest Common Substring (DP), Edit Distance, Valid Parentheses, Decode Ways, and Minimum Window Substring are popular interview problems.'
    ELSE description
  END
WHERE name IN ('Arrays', 'Linked Lists', 'Stacks', 'Queues', 'Trees', 'Graphs', 'Dynamic Programming',
               'Sorting Algorithms', 'Searching Algorithms', 'Hashing', 'Recursion', 'Heaps', 'String Algorithms');
